version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install

  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - python3 -m poetry run black --check lasso
      # E501:
      #   We disable too long lines in ArrayType since the docstrings for arrays
      #   must be behind the arrays for sphinx, thus lines cannot be shortened.
      #   Anyhow if you find any way to change feel free to submit a PR.
      # E203:
      #   We ignore E203 since allowing whitespace around ':' makes slicing
      #   more understandable when doing complex slicing.
      # W503:
      #   Allowing operators such as '+' after a new line instead of putting it
      #   on the previous one, complex condition chains are more understandable.
      - |
        python3 -m poetry run flake8 lasso \
          --ignore="E203,W503" \
          --per-file-ignores="lasso/dyna/ArrayType.py:E501" \
          --show-source \
          --statistics \
          --count
      - python3 -m poetry run pylint lasso

  build:
    desc: Builds the puthon package
    cmds:
      - poetry build

  test:
    desc: Runs tests on the code
    cmds:
      - poetry run pytest
