version: "3"

tasks:
  setup:
    desc: Setup the development environment.
    cmds:
      - poetry install

  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - poetry run black --check .
      - poetry run ruff check .

  build:
    desc: Builds the python package
    cmds:
      - poetry build

  test:
    desc: Runs tests on the code
    cmds:
      - >
        poetry run pytest test
        --cov=lasso
        --cov-report=html

  docs:serve:
    desc: Serve the documentation locally for development and testing
    deps:
      - test
      - docs:changelog
    cmds:
      - poetry run mkdocs serve

  docs:build:
    desc: Build the documentation
    deps:
      - test
      - docs:changelog
    cmds:
      - poetry run mkdocs build

  docs:deploy:
    desc: Deploys the docs to GitHub (be careful!)
    deps:
      - test
      - docs:changelog
    cmds:
      - poetry run mkdocs gh-deploy

  docs:changelog:
    desc: Generates the changelog
    cmds:
      - >
        poetry run git-changelog .
        --output CHANGELOG.md
        --style angular
        --template angular
