site_name: LASSO-Python
site_url: https://open-lasso-python.github.io/lasso-python/
repo_url: https://github.com/open-lasso-python/lasso-python

theme:
  name: material

nav:
  - Home: index.md
  - Dyna:
      - Overview: dyna/index.md
      - D3plot: dyna/D3plot.md
      - D3plotHeader: dyna/D3plotHeader.md
      - ArrayType: dyna/ArrayType.md
      - FilterType: dyna/FilterType.md
      - Binout: dyna/Binout.md
      - Performance Info: dyna/performance_info.md
  - Femzip:
      - Overview: femzip/index.md
      - FemzipAPI: femzip/FemzipAPI.md
      - FemzipAPIStatus: femzip/FemzipAPIStatus.md
      - FemzipBufferInfo: femzip/FemzipBufferInfo.md
      - FemzipError: femzip/FemzipError.md
      - FemzipFileMetadata: femzip/FemzipFileMetadata.md
      - VariableInfo: femzip/VariableInfo
      - FemzipVariableCategory: femzip/FemzipVariableCategory.md
  - Diffcrash:
      - Overview: diffcrash/diffcrash.md
      - CLI: diffcrash/run.md
      - Code: diffcrash/diffcrash_run.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
  - coverage

markdown_extensions:
  - admonition
  # Code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
